### ISSUE TITLE
HOME：TODO

### ISSUE THREAD

**Issue by youbinoyou** [TeamSunstripe/ShimokitaInfo#2]
**関連情報**
#1 

**HOMEを考える**

**TODO**
- [ ] 表示するものについて
----

**表示するものについて**

**header**
- [ ] メインメニュー - サブ右メニュー - サブ左メニュー #7 

**contents**
- [ ] ランキング - デイリーランキング：カテゴリ別：タレントコンテンツ：概要 #9
- [ ] 検索
- [ ] ニュース（お知らせ） - 日付 - お知らせ：概要 → お知らせ：詳細
- [ ] イベントカレンダー - Google カレンダーに追加
- [ ] コンテンツ概要/宣伝 - タレント組数 / タレント登録数 / Apple or android
- [ ] 法人の方々へ - オーディション開催 / 企業タイアップ：イベント製作・キャスティング / アプリ参加 / 法人お問い合わせフォーム
- [ ] INFOMATION SNSへのリンク

**footer**
- [ ] タイムライン
- [ ] ランキング
- [ ] 登録有名人
- [ ] 法人の方へ / 法人の方へ：概要：法人お問い合わせフォーム
- [ ] コンテンツについて

**other**
- [ ] copy right
- [ ] よくある質問
- [ ] 利用規約
- [ ] プライバシーポリシー
- [ ] 特定商取引法に基づく表示
- [ ] 資金決済法に基づく表示
- [ ] プレスリリース
